# Generated by Django 2.2.5 on 2020-05-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('levels', models.CharField(blank=True, max_length=11, null=True)),
                ('likes', models.CharField(blank=True, max_length=11, null=True)),
                ('pageno', models.CharField(blank=True, db_column='pageNo', max_length=11, null=True)),
            ],
            options={
                'db_table': 'story',
                'managed': False,
            },
        ),
    ]
